name: automatically merge sync PR's
on:
  pull_request:
    branches: [ development ]

jobs:
  approve-merge-sync-prs:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'main' }}
    permissions:
      pull-requests: write
    steps:
      - name: auto-approve-pull-request
        uses: hmarr/auto-approve-action@v3
    
  auto-merge-sync-prs:
    runs-on: ubuntu-latest
    needs: approve-merge-sync-prs
    if: ${{ github.head_ref == 'main' }}
    steps:
   
    - name: merge-pull-request
      uses: KeisukeYamashita/auto-pull-request-merge@v1
      with:
        intervalSeconds: 10
        timeoutSeconds: 30
        labels: auto-sync-merge
        token: ${{ secrets.GITHUB_TOKEN }}
        checkStatus: true
