name: concurrency check
on: 
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}  
  
jobs:
  concurrency-check-job:
    runs-on: ubuntu-latest
    steps: 
      - name: echo workflow name
        run: echo ${{ github.workflow }}
      - run: echo ${{ github.ref_name }}
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
        
