name : context demo
on:
  workflow_dispatch:
    inputs:
      text:
        description: 'enter the word you want to print'
        default: 'Hello'
        required: true
        type: string

env:
  firstName : 'Amuthan'
  website   : 'testing mini bytes'

jobs:
  contexts-demo:
    timeout-minutes: 5
    continue-on-error: false
    container:
      image: alpine:latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ubuntu-latest]
    steps:
      - run: echo ${{ inputs.text }}
      - run: echo ${{ github.event.inputs.text }}
      - run: echo ${{ github.actor }}
      - run: echo 'Hi ${{ env.firstName }}'
      - run: echo 'website - ${{ env.website }}'
      - run: echo ${{ job.status}}
      - run: echo ${{ runner.os}}
      - run: echo ${{ secrets.PASSWORD }} ${{ env.firstName }}
        env:
          firstName : 'Testing'


  contexts-demo-2:
    needs: [contexts-demo]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'contexts-demo-2 running after contexts-demo'

  job3:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [ contexts-demo ]
    steps:
      - run: echo 'job3'
  job4:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [ contexts-demo ]
    steps:
      - run: echo 'job4'