name: run web test in github actions

on: workflow_dispatch
jobs:
  run-web-test:
    runs-on: ubuntu-latest

    steps:
      - name: pull the project in to the runner
        uses: actions/checkout@v3

      - name: set  up java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: store docker image cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        continue-on-error: true
        with:
          step: restore

      - name: run the web test
        run: |
          mvn clean test -Pweb -Dusername=${{secrets.USERNAME}}

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        continue-on-error: true
        with:
          step: save