name: run the workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true
  repository_dispatch:
    types: [ my-event ]

jobs:
  build:
    name: run-workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: print trigger details
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.client_payload.github.action }}
          echo ${{ github.event.client_payload.github.actor }}
          echo ${{ inputs.name }}
